version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: deathnote_user
      POSTGRES_PASSWORD: 1231
      POSTGRES_DB: deathnote_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SERVER_PORT: "8080"
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: butiti
      DB_PASSWORD: "1231"
      DB_NAME: butiti
      DB_SSLMODE: disable
    ports:
      - "8080:8080"
    command: ["./deathnote"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
